### ISSUE TITLE
I hope we'll see these features soon

### ISSUE THREAD

**Issue by ahm631** [chrishubert/whatsapp-web-api#4]
Great job, Christophe! I hope we'll see these benefits soon."

Send Image Message
Send Video Message
Send Audio Message
Send Document Message
Send File URL
Send Button(Template) Message
Send Contact Message
Send List Message
Set Status
Send Button With Media
Is On Whatsapp?
Download Profile Pic
User Status
Block/Unblock User
Update Profile Picture

Create Group
Leave Group
All Groups
Invite User
Make Admin
Demote Admin
Group Invite Code
All Groups
Update Group Participants
Update Group Setting
Update Group Subject
Update Group Description

Thank you for your effort.

**Comment by chrishubert** [comment]
@ahm631 thanks for this! 
I'll work on those indeed (they are already supported by the original library and should be able to be ported)
If you have time, you can also submit a PR for review 👍
Don't forget to star the repo, it helps my motivation 😅

**Comment by chrishubert** [comment]
Quick Update on this issue:

| Done | Action |
| --- | --- |
| [X] | Send Image Message |
| [X] | Send Video Message |
| [X] | Send Audio Message |
| [X] | Send Document Message |
| [X] | Send File URL |
| [ ] | Send Button(Template) Message |
| [ ] | Send Contact Message |
| [ ] | Send List Message |
| [ ] | Set Status |
| [ ] | Send Button With Media |
| [X] | Is On Whatsapp? |
| [X] | Download Profile Pic |
| [ ] | User Status |
| [ ] | Block/Unblock User |
| [ ] | Update Profile Picture |
| [ ] | Create Group |
| [ ] | Leave Group |
| [ ] | All Groups |
| [ ] | Invite User |
| [ ] | Make Admin |
| [ ] | Demote Admin |
| [ ] | Group Invite Code |
| [ ] | Update Group Participants |
| [ ] | Update Group Setting |
| [ ] | Update Group Subject |
| [ ] | Update Group Description |

**Comment by ahm631** [comment]
You're doing a great job! Keep up the hard work!

**Comment by ramphy** [comment]
Nice job!

**Comment by chrishubert** [comment]
I moved the content to the `README.MD` for better visibility.
I'm closing this issue for now – feel free to reopen, if more requests 🎉
